const _ = require('lodash'),
    accountSummary = require("./modules/accountSummary/api")(),
    activityLogs = require("./modules/activityLogs/api")(),
    addPlasticCard = require("./modules/addPlasticCard/api")(),
    cachecontrols = require("./modules/cachecontrols/api")(),
    changeOfEvent = require("./modules/changeOfEvent/api")(),
    contract = require("./modules/contract/api")(),
    delivery = require("./modules/delivery/api")(),
    eventCreation = require("./modules/eventCreation/api")(),    
    eventdetails = require("./modules/eventdetails/api")(),
    addAddress = require("./modules/eventManagement/addAddress/api")(),
    closingGiftPriceRange = require("./modules/eventManagement/closingGiftPriceRange/api")(),
    editAddress = require("./modules/eventManagement/editAddress/api")(),
    editEventInfo = require("./modules/eventManagement/EditEventInfo/api")(),
    employeeCardInfo = require("./modules/eventManagement/EmployeeCardInfo/api")(),
    eventAddress = require("./modules/eventManagement/eventAddress/api")(),
    eventGralInfo = require("./modules/eventManagement/EventGralInfo/api")(),
    failedTransferences = require("./modules/eventManagement/failedTransferences/api")(),
    fraudManagement = require("./modules/eventManagement/fraudManagement/api")(),
    getAccountPartialTransferDetails = require("./modules/eventManagement/getAccountPartialTransferDetails/api")(),
    getEventAccountStatementDetails = require("./modules/eventManagement/getEventAccountStatementDetails/api")(),
    getGiftsAndPurchases = require("./modules/eventManagement/getGiftsAndPurchases/api")(),
    header = require("./modules/eventManagement/Header/api")(),
    notes = require("./modules/eventManagement/notes/api")(),
    openingGift = require("./modules/eventManagement/openingGift/api")(),
    plasticCard = require("./modules/eventManagement/plasticCard/api")(),
    prefferedDeliveryday = require("./modules/eventManagement/preferredDeliveryDay/api")(),
    getState = require("./modules/dashboard/api")(),
    labels = require("./modules/labels/api")(),
    user = require("./modules/user/api")(),
    reports =require("./modules/reports/api")(),
    returns = require("./modules/return/api")(),
    verificationDoc = require("./modules/verificationDocuments/api")(),
    printapi = require("./modules/print/api")(),
    predeterminedList = require("./modules/predeterminedLists/api")(),
    eventSearch = require("./modules/eventsearch/api")(),
    eventManagementAddGift = require("./modules/eventMangementGiftList/addGiftItemBySKUID/api")(),
    eventManagementGetRegalos =  require("./modules/eventMangementGiftList/getRegalosRegistrados/api")(),
    eventManagementPerPurchase = require("./modules/eventMangementGiftList/personalPurchase/api")(),
    eventManagementRegaloRecib = require("./modules/eventMangementGiftList/regaloRecibidos/api")(),

    Routes = _.unionBy(accountSummary,activityLogs,
        addPlasticCard,cachecontrols,changeOfEvent,contract,delivery,
        eventCreation,eventdetails,addAddress,closingGiftPriceRange,editAddress,
        editEventInfo,employeeCardInfo,eventAddress,eventGralInfo,failedTransferences,
        fraudManagement,getAccountPartialTransferDetails,getEventAccountStatementDetails,
        getGiftsAndPurchases,header,notes,openingGift,getState,
        labels,user,reports,returns,verificationDoc,printapi,
        predeterminedList,eventSearch,eventManagementAddGift,eventManagementGetRegalos,eventManagementPerPurchase,eventManagementRegaloRecib,plasticCard,prefferedDeliveryday);

 export const ApiRoutes = Routes;