import React from 'react';
import appconfig from '../../../../config/appconfig'
export const strategy = {
  strategies: {
    Celebraciones: {
      types: {
        [appconfig.eventTypes.Boda]: {
          name: 'Boda',
          nameInEnglish: 'Wedding',
          coownerOptional: false,
          assignRole: true,
          selectionEnable: true,
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Bebè]: {
          name: 'Bebè',
          nameInEnglish: 'Baby',
          coownerOptional: true,
          selectionEnable: true,
          assignRole: true,
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.XV_Anòs]: {
          name: 'XV Anòs',
          nameInEnglish: 'Sweet_Fifteen',
          coownerOptional: false,
          assignRole: false,
          selectionEnable: false,
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.First_Communion]: {
          name: 'First Communion',
          nameInEnglish: 'First_Communion',
          coownerOptional: false,
          assignRole: false,
          selectionEnable: false,
          type: 'ceremony',
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Baptism]: {
          name: 'Baptism',
          nameInEnglish: 'Baptism',
          coownerOptional: false,
          assignRole: false,
          selectionEnable: false,
          type: 'ceremony',
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Confirmaciòn]: {
          name: 'Confirmaciòn',
          nameInEnglish: 'Confirmation',
          coownerOptional: false,
          assignRole: false,
          selectionEnable: false,
          type: 'ceremony',
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Other_Religious_Ceremonies]: {
          name: 'Other Religious Ceremonies',
          nameInEnglish: 'Other_Religious_Ceremonies',
          assignRole: false,
          coownerOptional: false,
          selectionEnable: false,
          type: 'ceremony',
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Bar_Mitzvah]: {
          name: 'Bar Mitzvah',
          nameInEnglish: 'Bar_Mitzvah',
          coownerOptional: false,
          assignRole: false,
          selectionEnable: false,
          type: 'ceremony',
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Bat_Mitzvah]: {
          name: 'Bat Mitzvah',
          nameInEnglish: 'Bat_Mitzvah',
          coownerOptional: false,
          assignRole: false,
          selectionEnable: false,
          type: 'ceremony',
          coOwnerDynamic: false,
        },
      },
    },
    Todo_tipo_de_eventos: {
      englishName: 'openEvent',
      types: {
        [appconfig.eventTypes.Open_House]: {
          name: 'Open House',
          assignRole: true,
          coownerOptional: true,
          selectionEnable: true,
          coOwnerDynamic: true,
        },
        [appconfig.eventTypes.Fiesta_Reunión]: {
          name: 'Fiesta/Reunión',
          assignRole: true,
          selectionEnable: true,
          coownerOptional: true,
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Fiesta_infantil]: {
          name: 'Fiesta infantil',
          selectionEnable: false,
          textField: true,
          assignRole: true,
          coownerOptional: true,
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Aniversario]: {
          name: 'Aniversario',
          nameInEnglish: 'Anniversary',
          selectionEnable: true,
          coownerOptional: false,
          assignRole: true,
          coOwnerDynamic: false,
        },
        [appconfig.eventTypes.Cumpleaños]: {
          name: 'Cumpleaños',
          assignRole: true,
          coownerOptional: true,
          selectionEnable: true,
          coOwnerDynamic: true,
        },
        [appconfig.eventTypes.Despedida]: {
          name: 'Despedida',
          assignRole: true,
          coownerOptional: true,
          selectionEnable: true,
          coOwnerDynamic: true,
        },
        [appconfig.eventTypes.Others]: {
          name: 'Others',
          nameInEnglish: 'Others',
          assignRole: true,
          selectionEnable: true,
          coownerOptional: true,
          coOwnerDynamic: true,
        },
        [appconfig.eventTypes.Mascotas]: {
          name: 'Mascotas',
          nameInEnglish: 'Mascotas',
          assignRole: true,
          selectionEnable: true,
          coownerOptional: true,
          coOwnerDynamic: true,
        },
      },
    },
  },
}
