import routeconfig from './routeconfig'

const clientSettings = global && global.clientSettings
export default {
  app: {
    head: {
      title: 'Tienda - Mesa De Regalos | Liverpool es parte de MI vida',
      description: 'Tienda - Mesa De Regalos | Liverpool es parte de MI vida',
      meta: [
        { name: 'description', content: 'Tienda - Mesa De Regalos | Liverpool es parte de MI vida' },
        { charset: 'utf-8' },
        { property: 'og:site_name', content: 'Liverpool es parte de MI vida' },
        { property: 'og:image', content: '' },
        { property: 'og:locale', content: 'es_MX' },
        { property: 'og:title', content: 'Tienda - Mesa De Regalos | Liverpool es parte de MI vida' },
        { property: 'og:description', content: 'Tienda - Mesa De Regalos | Liverpool es parte de MI vida' },
        { property: 'og:card', content: 'summary' },
        { property: 'og:site', content: '@liverpool.com.mx' },
        { property: 'og:creator', content: '@liverpool.com.mx' },
        { property: 'og:image:width', content: '200' },
        { property: 'og:image:height', content: '200' },
      ],
    },
  },
  version: global && global.version,
  assets: clientSettings && clientSettings.assets,
  ico: clientSettings && clientSettings.ico,
  bundleCSS: clientSettings && clientSettings.bundleCSS,
  defaultError: {
    status: {
      status: 'failure',
      errorCode: '500',
      errorMessage: 'No ha sido posible completar la operación solicitada, espere unos minutos y vuelva a intentarlo.',
    },
  },
  loadingImage: '//assets.liverpool.com.mx/assets/images/ajax-loader.gif',
  defaultImage: clientSettings && `${clientSettings.assets}/images/gift.png`,
  imageUrl: clientSettings && `${clientSettings.assets}/images/addImageIcon.png`,
  eventStatusUpdate: {
    status: 'failure',
  },
  employeeCardBinRanges: ['5300', '6300', '7300', '8300'],
  eventStatusCodes: {
    active: 'Activo',
    extemporaneousEvent: 'Evento Extemporaneo',
    suspended: 'Suspendido',
    closed: 'Cerrado',
    adminProcess: 'Proceso Administrativo',
    suspendedByTime: 'Suspendido por Tiempo',
    deleted: 'Eliminado',
    deletedByFraud: 'Eliminado por Fraude',
    tempClosed: 'Cierre Temporal',
  },
  eventCategory: {
    CELEBRATION: 'Para el Gran Día',
    OPENEVENT: 'Para Toda Ocasión',
  },
  storeModalRoles: ['Corporativo A', 'Corporativo B', 'Fraudes'], // this will have to come from backend in Phase 2.
  labelPageNames: [
    'editEvent',
    'editEventDelivery',
    'Event management contract page',
    'Event management employee card page',
    'editEventPrefreneces',
    'Event management event type change',
    'Event management dashboard',
    'RegalosRegistradosPage',
    'PredeterminedPage',
    'RegalosRecibidosPage',
    'compraspersonalesPage',
    'Event Category and Type Selection page',
    'Owner email verification page',
    'createEventStep1',
    'categoryLanding',
    'Event creation stage 1',
    'Event creation stage 2',
    'Event creation stage 3',
    'Event creation stage 4',
    'Event Creation plastic card page',
    'Event Creation dilisa card page',
    'loginPage',
    'Password expiring page',
    'homePage',
    'noPermissionPage',
    'noResultsPage',
    'eventAccountStatement',
    'Physical Gifts Details Page',
    'Personal Gifts Details Page',
    'Bonus Details Page',
    'Partial transference Page',
    'Event Account Landing page – Vales system down',
    'Electronic Gifts Details Page',
    'In transit – Pop up',
    'Retiro Anticipado Landing Page',
    'transference success page',
    'transference success page (bank)',
    'Success page when user saves new bank account to profile',
    'Closure pop up',
    'Closure pop up (no Lp card)',
    'validate physical wallet number',
    'event closure confirmation page',
    'event closure success page',
    'event statement page',
    'Estado de Cuenta Page',
    'Close Event - Combination of Liverpool card and bank account',
    'event statement page for physical items',
    'giftregistry_errors',
    'Return Landing Page',
    'Refund Confirmation Page',
    'Closure Landing Page',
  ],

  celebLabels: {
    festejado: 'festejado',
    organizador: 'organizador',
  },

  eventTypes: {
    Boda: 'Boda',
    Bebè: 'Bebé',
    XV_Anòs: 'XV años',
    Bar_Mitzvah: 'Bar Mitzvah',
    Bat_Mitzvah: 'Bat Mitzvah',
    Baptism: 'Bautizo',
    First_Communion: 'Primera Comunión',
    Confirmaciòn: 'Confirmación',
    Other_Religious_Ceremonies: 'Otras Ceremonias Religiosas',
    Fiesta_Reunión: 'Fiesta/ Reunión',
    Fiesta_infantil: 'Fiesta Infantil',
    Cumpleaños: 'Cumpleaños',
    Despedida: 'Despedida',
    Open_House: 'Open House',
    Aniversario: 'Aniversario',
    Others: 'Otros',
    Mascotas: 'Mascotas',
  },

  states: {
    Distrito_Federal: 'DISTRITO FEDERAL',
    Cdmx: 'CDMX/ZONA METROPOLITANA',
  },

  printableComponents: [
    routeconfig.globalstepg,
    routeconfig.updatedcontract,
    routeconfig.eventcontract,
    routeconfig.statementaccountsummary,
    routeconfig.physicalgiftsdetail,
    routeconfig.personalpurchasesdetail,
    routeconfig.electronicgiftsdetail,
    routeconfig.bonusdetail,
    routeconfig.statementpartialtransference,
  ],
}
