export default {
  downloadPrint: 'downloadprint',

  employeenocard: 'employeenocard',
  partialemployeenocard: 'partialemployeenocard',

  // closureewalletsummary: 'closureewalletsummary',
  // ClosureTransference: 'ClosureTransference',
  partialewalletsummary: 'partialewalletsummary',
  transferancecombinedsummary: 'transferancecombinedsummary',

  accountinfocelebrated1: 'accountinfocelebrated1',
  accountinfocelebrated2: 'accountinfocelebrated2',
  accountinfocelebrated3: 'accountinfocelebrated3',
  accountinfocelebrated4: 'accountinfocelebrated4',
  addnewaddress: 'addnewaddress',
  editaddress: 'editaddress',
  multipleaddressselection: 'multipleaddressselection',
  singleaddressselection: 'singleaddressselection',
  cardassigment: 'cardassigment',
  basicform: 'basicform',
  basicform2: 'basicform2',
  basicform3: 'basicform3',
  basicformfull: 'basicformfull',
  basicformfull2: 'basicformfull2',
  basic: 'basicformfull3',
  formmanagement: 'formmanagement',
  formmanagement3: 'formmanagement3',
  formmanagementfull: 'formmanagementfull',
  formmanagementfull3: 'formmanagementfull3',
  formsimple: 'formsimple',
  formsimple3: 'formsimple3',
  formsimplefull: 'formsimplefull',
  formsimplefull3: 'formsimplefull3',
  mixins: 'mixins',
  contract: 'contract',
  deliverypreferences: 'deliverypreferences',
  addnewcreditcard: 'addnewcreditcard',
  employeecreditcardinfo: 'employeecreditcardinfo',
  eventinputinfo: 'eventinputinfo',
  inputemailcelebrated: 'inputemailcelebrated',
  selectgrtype: 'selectgrtype',
  //   defaultlist: 'defaultlist',
  //   defaultlistdetail: 'defaultlistdetail',
  personalpurchase: 'personalpurchase/:eventId',
  receivedgifts: 'receivedgifts/:eventId',
  registermodal: 'registermodal',
  successregistermodal: 'successregistermodal',
  registeredgifts: 'registeredgifts/:eventId',
  // registeredgifts: 'registeredgifts',


  // addnewemployeecard: 'addnewemployeecard/:eventId',
  // editemployeecard: 'editemployeecard/:eventId',
  // employeecards: 'employeecards',
  // addnewaddress2: 'addnewaddress2/:eventId',
  // editaddress2: 'editaddress2/:eventId/:addressId',
  // eventaddressinfo: 'eventaddressinfo/:eventId',
  // editeventinfo: 'editeventinfo',
  // eventgralinfo: 'eventgralinfo',
  calendarmodal: 'calendarmodal',
  permissionsmodal: 'permissionsmodal',
  storemodal: 'storemodal',
  dataresulttest: 'dataresulttest',
  movements: 'movements',

  EventDetails: 'EventDetails/:eventId',
  registermodal2: 'registermodal2',
  successregistermodal2: 'successregistermodal2',

  addnewmanager: 'addnewmanager',
  celebratedcardinfo: 'celebratedcardinfo',
  changeofevent: 'changeofevent',
  eventinfo: 'eventinfo',
  updatedcontract: 'updatedcontract',
  selectaddress: 'selectaddress',
  selectaddress2: 'selectaddress2',
  selectedcelebrated: 'selectedcelebrated',
  selecteventtype: 'selecteventtype',


  // Browse & Navigate
  root: '/',
  login: 'login',
  updatepassword: 'updatepassword',
  updatepasswordnow: 'updatepasswordnow',
  daytracker: 'daytracker',
  maindashboard: 'maindashboard',
  eventsearch: 'eventsearch',

  // Event Creation
  globalstepa: 'event/stepa',
  globalstepb: 'event/stepb',
  globalstepc: 'event/stepc',
  globalstepd: 'event/stepd',
  globalstepe: 'event/stepe',
  globalstepf: 'event/stepf',
  globalstepg: 'event/stepg',
  globalsteph: 'event/steph/:eventId',
  globalstepi: 'event/stepi',

  // Event Management
  eventdashboard: 'eventdashboard/:eventId',
  editeventinfo: 'eventdashboard/editeventinfo/:eventId/:celebrityIndex',
  addeventinfo: 'eventdashboard/addeventinfo/:eventId',
  eventgralinfo: 'eventdashboard/eventgralinfo/:eventId',
  eventaddressinfo: 'eventdashboard/eventaddressinfo/:eventId',
  addnewaddress2: 'eventdashboard/addnewaddress2/:eventId',
  editaddress2: 'eventdashboard/editaddress2/:eventId/:addressId',
  preferences: 'eventdashboard/preferences/:eventId',
  eventcontract: 'eventdashboard/contract/:eventId',
  verificationdocuments: 'eventdashboard/verification/:eventId',
  employeecards: 'eventdashboard/employeecards/:eventId',
  addnewemployeecard: 'eventdashboard/addnewemployeecard/:eventId',
  editemployeecard: 'eventdashboard/editemployeecard/:eventId',
  // preferences: 'eventdashboard/preferences/:eventId',

  // Account Tranference and Closure
  electronicgiftsdetail: 'electronicgiftsdetail/:eventId',
  personalpurchasesdetail: 'personalpurchasesdetail/:eventId',
  physicalgiftsdetail: 'physicalgiftsdetail/:eventId',
  bonusdetail: 'bonusdetail/:eventId',
  statementaccountsummary: 'statementaccountsummary/:eventId',
  statementaccountdownloadprint: 'statementaccountdownloadprint',
  intransitmodal: 'intransitmodal/:eventId',
  statementpartialtransference: 'statementpartialtransference/:eventId',
  partialconfirmation: 'partialconfirmation/:eventId',
  partialtransference: 'partialtransference/:eventId',
  closuretransference: 'closuretransference/:eventId',
  closureconfirmation: 'closureconfirmation/:eventId',

  // END Account Tranference and Closure
  PredeterminedLists: 'PredeterminedLists/:eventId/:brand',
  PredeterminedListsDetailsWeb: 'PredeterminedListsDetailsWeb/:eventId/:repoId/:brand',
  reportsummary: 'reportsummary',
  AddBallotModal: 'AddBallotModal',
  DeleteBallotModal: 'DeleteBallotModal',
  downloadPdf: 'modaltest',

  // Return and refunds
  searchforreturn: 'searchforreturn/:eventId',
  RefundsLandingPage: 'RefundsLandingPage/:eventId',
  ReturnRefundConfirmation: 'ReturnRefundConfirmation',

  // Utilities
  flushcache: 'flushcache',
  deletecache: 'deletecache',
  healthcheck: 'healthcheck',
  instancecheck: 'instancecheck',
};
