import config from "config/appconfig";

const services = (gr, commerce, shoapp, otpapp) => ({
  // all pages
  "/api/labels": `${gr}/regalos/services/browseNavigation/staticLabels?links=none`,

  // browse & navigate
  "/api/login": `${gr}/instore/grInstore/storeUserLogin?links=false`,
  "/api/logout": `${gr}/instore/grInstore/logout?links=false`,
  "/api/saveStoreDetails": `${gr}/instore/grInstore/saveStoreDetails?links=false`,
  "/api/getActivityLog": `${gr}/instore/activityLog/activityLogDetails?links=false`,
  "/api/daytrack": `${gr}/instore/activityLog/activityLogDetails?links=false`,
  "/api/updatepassword": `${gr}/instore/grInstore/updatePassword?links=false`,
  "/api/getEventsBySearchablePropertiesPerStore": `${gr}/regalos/services/browseNavigation/eventBySearhableProperties?links=none`,
  "/api/getStateList": `${gr}/regalos/services/EventCreation/stateList?links=0`,
  "/api/getStoreList": `${gr}/regalos/services/EventCreation/storeList?links=0`,

  // event creation and management
  "/api/failedTransferences": `${gr}/instore/manageEvent/failedTransferences?links=none`,
  "/api/DayoftheWeekForAddress": `${gr}/regalos/services/EditEvent/DayoftheWeekForAddress?links=false`,
  "/api/getPreferenceDeliveryAddress": `${gr}/regalos/services/EditEvent/preferredDeliveryDayDetails?links`,
  "/api/getEventCategories": `${gr}/regalos/services/EventCreation/eventCategories?links=false`,
  "/api/categorySpecificEvents": `${gr}/regalos/services/EventCreation/categorySpecificEvents?links`,
  "/api/isProfileVerified": `${commerce}/public/v1/currentUser/isProfileVerified?links=false`,
  "/api/coOwnerEligible": `${gr}/regalos/services/EventCreation/isCoOwnerEligible?links=false`,
  "/api/createProfile": `${commerce}/public/v1/currentUser/create?links=none`,
  "/api/saveOwnerDetails": `${gr}/regalos/services/EditEvent/saveOwnerDetails?links=null`,
  "/api/createEventAddAddress": `${commerce}/public/v1/currentUser/instoreNewDeliveryAddress?links=false`,
  "/api/createEventUpdateAddress": `${commerce}/public/v1/currentUser/instoreUpdateDeliveryAddress?links=false`,
  "/api/addAddress": `${commerce}/public/v1/currentUser/instoreNewDeliveryAddress?links=false`,
  "/api/deliveryPreference": `${gr}/regalos/services/EditEvent/preferredDeliveryDayDetails?links=false`,
  "/api/contract": `${gr}/regalos/services/EditEvent/ContractDetails?links=false`,
  "/api/createEvent": `${gr}/regalos/services/EventCreation/createEvent?links=false`,
  "/api/addressSearch": `${gr}/regalos/services/EditEvent/addressSearch?links=false`,
  "/api/addDilisaCard": `${gr}/instore/manageEvent/addandUpdateDilisaCard?links=none`,
  "/api/displayDilisaCard": `${gr}/instore/manageEvent/displayDilisaCard?links=none`,
  "/api/addAndUpdateDilisaCard": `${gr}/instore/manageEvent/addandUpdateDilisaCard?links=none`,
  "/api/addAndUpdateEmployeeCard": `${gr}/instore/manageEvent/addandUpdateDilisaCard?links=none`,
  "/api/removeDilisaCard": `${gr}/instore/manageEvent/removeDilisaCard?links=false`,
  "/api/getDeliveryAddressesForInstore": `${commerce}/public/v1/currentUser/getAddresses?links=false`,
  "/api/validateEventName": `${gr}/regalos/services/EventCreation/validateEventName?links=false`,
  "/api/openingGiftForEvent": `${gr}/regalos/services/EditEvent/setOpeningOrClosingGiftForEvent?links`,
  "/api/openingOrClosingGiftDetailsForEvent": `${gr}/regalos/services/EditEvent/getOpeningOrClosingGiftForEvent?links`,
  "/api/getClosingGiftPriceRange": `${gr}/regalos/services/EditEvent/ClosingGiftPriceRange?links`,
  "/api/createNotes": `${gr}/instore/manageEvent/createNotes?links`,
  "/api/displayNotes": `${gr}/instore/manageEvent/displayNotes?links`,
  "/api/deleteNotes": `${gr}/instore/manageEvent/deleteNotes?links`,
  "/api/getEventDetails": `${gr}/regalos/services/EditEvent/eventDetails?links=null`,
  "/api/getGiftsAndPurchases": `${gr}/instore/manageEvent/getGiftsAndPurchases?links=none`,
  "/api/getEventAccountStatementDetails": `${gr}/regalos/services/eventStatement/eventAccountStatementDetails?links`,
  "/api/getAccountPartialTransferDetails": `${gr}/regalos/services/eventStatement/accountPartialTransferDetails?links=null`,
  "/api/fetchPlasticCards": `${gr}/instore/manageEvent/fetchPlasticCard?links=none`,
  "/api/deletePlasticCards": `${gr}/instore/manageEvent/removePlasticCard?links=none`,
  "/api/addPlasticCard": `${gr}/instore/manageEvent/addPlasticCard?links`,
  "/api/getEventDocuments": `${gr}/instore/manageEvent/displayVerificationDocuments?links=false`,
  "/api/removeEventDocument": `${gr}/instore/manageEvent/removeVerificationDocuments?links=false`,
  "/api/uploadEventDocument": `${gr}/instore/manageEvent/addVerificationDocuments?links=false`,
  "/api/updateBonusSelection": `${gr}/instore/eventGiftList/updateBonusSelection?links=none`,
  "/api/getAdressSearch": `${gr}/regalos/services/EditEvent/addressSearch?links=none`,
  "/api/deleteDeliveryAddresses": `${gr}/instore/manageEvent/deleteAddress?links=none`,
  "/api/assignAddress": `${gr}/regalos/services/EditEvent/AddressCelebrityMapping?links`,
  "/api/addAddressGR": `${gr}/regalos/services/EditEvent/EventDeliveryAddress?links`,
  "/api/EditAddressGR": `${gr}/instore/manageEvent/editEventAddress?links=none`,
  "/api/getEventDeliveryAddresses": `${gr}/regalos/services/EditEvent/EventDeliveryAddresses?links`,
  "/api/displayEventStatusDropdown": `${gr}/instore/manageEvent/displayEventStatusDropdown?links=none`,
  "/api/changeEventStatus": `${gr}/instore/manageEvent/changeStatus?links=none `,
  "/api/changeEmployeeEvent": `${gr}/instore/manageEvent/changeEmployeeEvent?links=false`,
  "/api/saveEventName": `${gr}/regalos/services/EditEvent/saveEventName?links=null`,
  "/api/setOwnerDetailsInSession": `${gr}/instore/manageEvent/setOwnerDetailsInSession?links=false`,
  "/api/saveEditEventInfo": `${gr}/regalos/services/EditEvent/saveOwnerDetails?links=null`,
  "/api/addEventInfo": `${gr}/regalos/services/EditEvent/addCoOwnerToEvent?links=none`,
  "/api/setEventDate": `${gr}/instore/manageEvent/editEventDate?links=none`,
  "/api/deleteAdministrator": `${gr}/regalos/services/EditEvent/removeCoOwner?links=none `,
  "/api/checkEventForFraud": `${gr}/regalos/services/fraudmanagement/checkEventForFraud?links=false`,
  "/api/updateEventStatus": `${gr}/regalos/services/fraudmanagement/updateEventStatus?links=false`,
  "/api/updateEventType": `${gr}/instore/manageEvent/updateEventType?links=none`,

  // gift list management
  "/api/getComprasPersonales": `${gr}/regalos/services/eventGiftList/getComprasPersonales?links=none`,
  "/api/eventGiftList/getRegalosRegistrados": `${gr}/regalos/services/eventGiftList/getRegalosRegistrados?links=none`,
  "/api/eventGiftlist/changeDeliveryAddress": `${gr}/regalos/services/eventGiftList/changeDeliveryAddress?links=false`,
  "/api/eventGiftlist/changeDeliveryMode": `${gr}/regalos/services/eventGiftList/changeDeliveryMode?links=false`,
  "/api/eventGiftList/addGiftItemBySKUID": `${gr}/instore/eventGiftList/addGiftItemBySKUID?links=false`,
  "/api/eventGiftList/removeItemsFromGiftlist": `${gr}/regalos/services/eventGiftList/removeItemsFromGiftlist?links=false`,
  "/api/eventGiftList/saveQuantity": `${gr}/regalos/services/eventGiftList/saveQuantity?links=false`,
  "/api/eventGiftList/setFavouriteGift": `${gr}/regalos/services/eventGiftList/setFavouriteGift?links=false`,
  "/api/getRegaloRecibidos": `${gr}/regalos/services/eventGiftList/getRegaloRecibidos?links=false`,
  "/api/getPurchaseTicketDetails": `${gr}/instore/eventGiftList/getPurchaseTicketDetails?links=none`,
  "/api/associatePurchaseTicket": `${gr}/instore/eventGiftList/associatePurchaseTicket?links=false`,
  "/api/dissociatePurchaseTicket": `${gr}/instore/eventGiftList/disassociatePurchasedTicket?links=no`,
  "/api/disassociatePurchasedTicketByButton": `${gr}/instore/eventGiftList/disassociatePurchasedTicketByButton?links=no`,
  "/api/getGiftListGuestView": `${gr}/regalos/services/eventGiftList/getGiftListGuestView?links=none`,
  "/api/predeterminedLandingPage": `${gr}/regalos/services/eventGiftList/getPredeterminedLandingPage?links=none`,
  "/api/predeterminedListPageHeaderInfo": `${gr}/regalos/services/eventGiftList/getPredeterminedListPageHeaderInfo?links=none `,
  "/api/predeterminedListPageItemsInfo": `${gr}/regalos/services/eventGiftList/getPredeterminedListPageItemsInfo?links=none`,
  "/api/addPredeterminedItem": `${gr}/regalos/services/eventGiftList/addPredeterminedItem?links=false`,
  "/api/getTrackOrder": `${gr}/regalos/services/eventGiftList/getTrackOrder?links=false`,
  "/api/getMessages": `${gr}/regalos/services/eventGiftList/getMessages?links=no`,
  "/api/addMessage": `${gr}/instore/eventGiftList/addMessage?links=no`,
  "/api/deleteMessage": `${gr}/instore/eventGiftList/deleteMessage?links=no`,
  "/api/getPredeterminedListPageHeaderInfo": `${gr}/regalos/services/eventGiftList/getPredeterminedListPageHeaderInfo?links=none`,
  "/api/savePurchaserName": `${gr}/instore/eventGiftList/savePurchaserName?links=no`,
  "/api/addAgainGiftItem": `${gr}/regalos/services/eventGiftList/addAgainGiftItem?links=no`,
  "/api/getReceivedGiftsMessages": `${gr}/instore/eventGiftList/getAllMessages?links=none`,
  "/api/validateRequiredOwners": `${gr}/instore/manageEvent/validateRequiredOwners?links=none`,

  // account summary
  "/api/accountStatementDetails": `${gr}/regalos/services/eventStatement/eventAccountStatementDetails?links=false`,
  "/api/StatementDetailsForPrintAndDownload": `${gr}/regalos/services/eventStatement/StatementDetailsForPrintAndDownload?links=false`,
  "/api/purchasedItemSummaryInfo": `${gr}/regalos/services/eventStatement/purchasedItemSummaryInfo?links=false`,
  "/api/purchasedItemsDetails": `${gr}/regalos/services/eventStatement/PurchasedItemsDetails?links=false`,
  "/api/bonusDetails": `${gr}/regalos/services/eventStatement/bonusDetails?links=false`,
  "/api/inTransit": `${gr}/regalos/services/eventStatement/inTransitDetails?links=false`,
  "/api/submitTransference": `${gr}/regalos/services/eventTransference/submitTransference?links=false`,
  "/api/verifyStoreAssociate": `${gr}/instore/grInstore/verifyStoreAssociate?links=false`,
  "/api/transferenceOptions": `${gr}/regalos/services/eventTransference/transferenceOptions?links`,
  "/api/calculateCommision": `${gr}/regalos/services/eventTransference/calculateCommision?links`,
  "/api/getEventSummaryInfo": `${gr}/regalos/services/eventGiftList/getEventSummaryInfo?links=false`,
  "/api/accountPartialTransferDetails": `${gr}/regalos/services/eventStatement/accountPartialTransferDetails?links=null`,
  "/api/deleteBankOrCardDetails": `${gr}/regalos/services/eventTransference/deleteBankOrCardDetails?links=false`,
  "/api/reAuthenticateUser": `${shoapp}/appclienteservices/services/v2/gifttable/accountstate/ReAuthenticateUser`,
  "/xapi/saveBankOrCardDetails": `${gr}/regalos/services/eventTransference/saveBankOrCardDetails?links=false`,
  "/api/getEwalletInfo": `${commerce}/public/v1/currentUser/getEwalletInfo?links=none`,
  "/api/initiateEventCloseProcess": `${gr}/regalos/services/eventClosure/initiateEventCloseProcess?links=false`,
  "/api/sendMail": `${gr}/regalos/services/eventStatement/sendMail?links=false`,

  // returns and refunds
  "/api/getInitiateReturnList": `${gr}/instore/returnrefundprocess/getInitiateReturnList?links=false`,
  "/api/deleteReturnItem": `${gr}/instore/returnrefundprocess/deleteReturnItem?links=false`,
  "/api/submitRefundTransaction": `${gr}/instore/returnrefundprocess/submitRefundTransaction?links=false`,

  // reports
  "/api/buildReportPage": `${gr}/instore/reporting/buildReportPage?links=false`,
  "/api/listUserFavoriteReports": `${gr}/instore/reporting/listUserFavoriteReports?links=false`,
  "/api/saveFavoriteReports": `${gr}/instore/reporting/saveReportAsFavorite?links=false`,
  "/api/deleteFavoriteReport": `${gr}/instore/reporting/deleteFavoriteReport?links=false`,
  "/api/retrieveFavoriteSelection": `${gr}/instore/reporting/retrieveFavoriteSelection?links=false`,
  "/api/generateReport": `${gr}/instore/reporting/generateReport?links=false`,

  //OTP Code
  "/api/otpAuthenticate": `${otpapp}/adapter-otp/authenticate`,
  "/api/otpCreateUser": `${otpapp}/adapter-otp/api/gr/user/create`,
  "/api/createDevice": `${otpapp}/adapter-otp/api/gr/device/create`,
  "/api/createOtp": `${otpapp}/adapter-otp/api/gr/otp/create`,
  "/api/validateOtp": `${otpapp}/adapter-otp/api/gr/otp/validate`,
});

export const cacheable = [
  "/api/labels",
  "/api/getStateList",
  "/api/getStoreList",
  "/api/getEventCategories",
  "/api/categorySpecificEvents",
  "/api/predeterminedLandingPage",
  "/api/buildReportPage",
];

export const brandNameServices = [
  "/api/reAuthenticateUser",
  "/api/isProfileVerified",
  "/api/createProfile",
  "/api/createEventAddAddress",
  "/api/createEventUpdateAddress",
  "/api/getDeliveryAddressesForInstore",
];

// export const preCacheable = [
//   '/api/labels',
//   '/api/getStateList',
//   '/api/getEventCategories',
//   '/api/categorySpecificEvents',
// ]

export const preCacheableServices = {
  eventCategories: "/api/getEventCategories",
  labels: "/api/labels",
  stateList_store: "/api/getStateList",
  stateList_advance: "/api/getStateList",
  categorySpecificEvents_Cele: "/api/categorySpecificEvents",
  categorySpecificEvents_Open: "/api/categorySpecificEvents",
};
export const preCacheableParams = {
  stateList_store: { searchType: "storeLogin" },
  stateList_advance: { searchType: "advanced" },
  labels: { pageNames: config.labelPageNames },
  categorySpecificEvents_Cele: {
    categoryType: config.eventCategory.CELEBRATION,
  },
  categorySpecificEvents_Open: { categoryType: config.eventCategory.OPENEVENT },
};

export default services;
