const API_MAP = {
  user_login_url: '/api/login',
  user_logout_url: '/api/logout',
  user_load_url: '/api/load-auth',
  update_password_url: '/api/updatepassword',
  get_activity_logs_url: '/api/getActivityLog',
  save_store_url: '/api/saveStoreDetails',
  get_adress_search: '/api/addressSearch',
  get_event_categories: '/api/getEventCategories',
  category_specific_events: '/api/categorySpecificEvents',
  verify_profile_url: '/api/isProfileVerified',
  create_profile_url: '/api/createProfile',
  validate_event_name: '/api/validateEventName',
  add_card_url: '/api/addDilisaCard',
  save_profile_details: '/api/saveOwnerDetails',
  add_address_url: '/api/createEventAddAddress',
  update_address_url: '/api/createEventUpdateAddress',
  get_addresses_url: '/api/getDeliveryAddressesForInstore',
  get_contract_details: '/api/contract',
  delivery_preference: '/api/deliveryPreference',
  create_event: '/api/createEvent',
  coOwner_eligible: '/api/coOwnerEligible',
  labels_url: '/api/labels',
  get_states_list_url: '/api/getStateList',
  get_store_list_url: '/api/getStoreList',
  get_plastic_card_url: '/api/fetchPlasticCards',
  delete_plastic_card_url: '/api/deletePlasticCards',
  add_plastic_card_url: '/api/addPlasticCard',
  add_Predetermined_Item: '/api/addPredeterminedItem',
  predetermined_Landing_Page: '/api/predeterminedLandingPage',
  validate_Required_Owner: '/api/validateRequiredOwners',
  update_Event_Type: '/api/updateEventType',
  // predetermined_List_Page_Header_Info: '/api/predeterminedListPageHeaderInfo',
  predetermined_List_Page_Items_Info: '/api/predeterminedListPageItemsInfo',
  get_registered_giftList: '/api/eventGiftList/getRegalosRegistrados',
  // get_registered_giftList: '/api/eventGiftList/getRegalosRegistrados',
  change_delivery_address: '/api/eventGiftlist/changeDeliveryAddress',
  change_delivery_mode: '/api/eventGiftlist/changeDeliveryMode',
  remove_gift: '/api/eventGiftList/removeItemsFromGiftlist',
  add_gift_item_by_sku: '/api/eventGiftList/addGiftItemBySKUID',
  save_quantity: '/api/eventGiftList/saveQuantity',
  set_favourite: '/api/eventGiftList/setFavouriteGift',
  get_build_report_page_data: '/api/buildReportPage',
  list_favorite_reports: '/api/listUserFavoriteReports',
  save_favorite_reports: '/api/saveFavoriteReports',
  delete_favorite_report: '/api/deleteFavoriteReport',
  retrieve_favorite_report: '/api/retrieveFavoriteSelection',
  generate_report: '/api/generateReport',
  generate_report_file: '/api/generateReportFile',
  get_PreferenceDeliveryAddress: '/api/getPreferenceDeliveryAddress',
  save_DayoftheWeekForAddress: '/api/DayoftheWeekForAddress',
  get_details: '/api/getEventDetails',
  get_GiftsAndPurchases: '/api/getGiftsAndPurchases',
  get_EventAccountStatementDetails: '/api/getEventAccountStatementDetails',
  get_closingGiftPriceRange: '/api/getClosingGiftPriceRange',
  get_Notes: '/api/displayNotes',
  delete_Notes: '/api/deleteNotes',
  set_NewNotes: '/api/createNotes',
  get_failedTransaction: '/api/failedTransferences',
  // get_adress_search: '/api/getAdressSearch',
  delete_delivery_addresses_url: '/api/deleteDeliveryAddresses',
  edit_address_url_GR: '/api/EditAddressGR',
  assign_address_url: '/api/assignAddress',
  get_credit_card_info: '/api/displayDilisaCard',
  get_event_details: '/api/getGiftListGuestView',
  set_favoutite_event: '/api/setFavouriteGift',
  edit_event: '/api/saveEditEventInfo',
  get_edit_event: '/api/getEditEventInfo',
  edit_event_name: '/api/saveEventName',
  set_event_date: '/api/setEventDate',
  delete_administrator: '/api/deleteAdministrator',
  add_address_url_GR: '/api/addAddressGR',

  display_event_status: '/api/displayEventStatusDropdown',
  change_event_status: '/api/changeEventStatus',
  set_dashboard_user: '/api/setOwnerDetailsInSession',
  add_event_info: '/api/addEventInfo',
  change_employee_event: '/api/changeEmployeeEvent',

  get_delivery_addresses_url: '/api/getEventDeliveryAddresses',
  // get_adress_search: '/api/getAdressSearch',
  // delete_delivery_addresses_url: '/api/deleteDeliveryAddresses',
  // edit_address_url: '/api/EditAddress',
  // assign_address_url: '/api/assignAddress',
  check_event_for_fraud: '/api/checkEventForFraud',
  update_event_status: '/api/updateEventStatus',


  // Account transference Closure
  getEventAccountStatementDetails: '/api/accountStatementDetails',
  getPurchasedItemSummaryInfo: '/api/purchasedItemSummaryInfo',
  getPurchasedItemsDetails: '/api/purchasedItemsDetails',
  getBonusDetails: '/api/bonusDetails',
  getInTransitDetails: '/api/inTransit',
  getTransferenceOptions: '/api/transferenceOptions',
  calculateCommision: '/api/calculateCommision',
  deleteBankOrCardDetails: '/api/deleteBankOrCardDetails',
  submitTransference: '/api/submitTransference',
  verifyStoreAssociate: '/api/verifyStoreAssociate',
  getEventSummaryInfo: '/api/getEventSummaryInfo',
  getaccountPartialTransferDetails: '/api/accountPartialTransferDetails',
  reAuthenticateUser: '/api/reAuthenticateUser',
  saveBankOrCardDetails: '/api/saveBankOrCardDetails',
  getEwalletInfo: '/api/getEwalletInfo',
  getStatementDetailsForPrintAndDownload: '/api/StatementDetailsForPrintAndDownload',
  initiateEventCloseProcess: '/api/initiateEventCloseProcess',
  sendMail: '/api/sendMail',

  get_openingOrClosingGiftDetailsForEvent: '/api/openingOrClosingGiftDetailsForEvent',
  set_openingGiftForEvent: '/api/openingGiftForEvent',
  get_employee_dilisa_card_details: '/api/displayDilisaCard',
  add_update_employee_card: '/api/addAndUpdateEmployeeCard',
  add_update_dilisa_card: '/api/addAndUpdateDilisaCard',
  remove_employee_card: '/api/removeDilisaCard',
  get_predetermined_list_header: '/api/getPredeterminedListPageHeaderInfo',
  save_purchaser_name: '/api/savePurchaserName',
  add_again_gift_item: '/api/addAgainGiftItem',
  get_all_messages: '/api/getAllMessages',
  get_initiate_return_list: '/api/getInitiateReturnList',
  submitRefundTransaction: '/api/submitRefundTransaction',
  delete_return_item: '/api/deleteReturnItem',
  get_Received_Gifts_Messages: '/api/getReceivedGiftsMessages',
  add_message: '/api/addMessage',
  delete_message: '/api/deleteMessage',

  flushcache: '/api/flushcache',
  deletecache: '/api/deletecache',

  // OTP Code
  otpAuthenticate: '/api/otpAuthenticate',
  otpCreateUser: '/api/otpCreateUser',
  createDevice: '/api/createDevice',
  createOtp: '/api/createOtp',
  validateOtp: '/api/validateOtp',

};
export default API_MAP;

